#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Runs CI in the docker dev container.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    ./docker/build --pull
    docker run --rm \
        --entrypoint scripts/cibuild \
        stacutils/stactools-package:latest-dev
fi
