FROM stactools-subpackage:latest

RUN conda install -c conda-forge pandoc

COPY . /src/stactools-subpackage
RUN pip install -r /src/stactools-subpackage/requirements-dev.txt
WORKDIR /src/stactools-subpackage
