ARG STACTOOLS_VERSION=latest
FROM ghcr.io/stac-utils/stactools:${STACTOOLS_VERSION}-dev

WORKDIR /opt/stactools-ephemeral

# For caching purposes, install dependencies but remove the actual ephemeral
COPY pyproject.toml requirements-dev.txt setup.cfg ./
COPY src/stactools/ephemeral/__init__.py src/stactools/ephemeral/
RUN pip install -r requirements-dev.txt \
    && pip install . \
    && rm -r /opt/conda/lib/python3.8/site-packages/stactools/ephemeral

COPY . ./
RUN pip install -e .
