#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ./scripts/format
        ./scripts/lint

        codespell -I .codespellignore -f \
            scripts/* \
            *.py ./**/*.py \
            *.md

        pytest --cov=stactools.ephemeral tests
        coverage xml
    fi
fi
