name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: true
    steps:
      - uses: actions/checkout@v4
      - name: Execute linters and test suites
        run: ./docker/cibuild
      - name: Upload All coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
  python-matrix:
    name: python-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda cache
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
          restore-keys: ${{ runner.os }}-conda-
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.*" 
      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Update Conda's environemnt
        run: conda env update -f environment.yml -n test
      - name: Install package
        run: uv sync
      - name: Execute linters and test suites
        run: uv run ./scripts/test
